### ISSUE TITLE
PDF always opens on p. 1!

### ISSUE THREAD

**Issue by Keks-Dose** [markus1189/org-pdfview#10]
Hi!

Linux, Orgmode 8.3.4, org-file with many links. 

I'd like to 
1. open via a given link from inside the org-file using C-c C-o 
2. the PDF with pdf-tools 
3. on a given page. 

The link is something like: [[./localfile.pdf::5][Description]]

Result: PDF is being opened, but always on p. 1 instead of e.g. page 5!

.emacs:
(eval-after-load 'org '(require 'org-pdfview))
(delete '("\.pdf\'" . default) org-file-apps)
(add-to-list 'org-file-apps '("\.pdf\'" . org-pdfview-open))
(add-to-list 'org-file-apps '("\.pdf::\([[:digit:]]+\)\'" . org-pdfview-open))

What am I doing the wrong way?

Same setup works under windows with other viewer. So probably there is an 
error in those lines above. Any hints? -- Thank you!

**Comment by markus1189** [comment]
Unfortunately I won't be able to test this until the weekend, so until then I will try to guess what the problem is ;)

Your elisp for emacs looks like you are missing some backslashes inside the strings, e.g.

`(add-to-list 'org-file-apps '("\.pdf\'" . org-pdfview-open))`

here you only have `\.` while it should be `\\.` like this:

`(add-to-list 'org-file-apps '("\\.pdf\\'" . org-pdfview-open))`

**Comment by Keks-Dose** [comment]
I have no idea, why the code was copied from my .emacs without double backlashes, but the lines in my .emacs are:

``` lisp
(eval-after-load 'org '(require 'org-pdfview))
(delete '("\\.pdf\\'" . default) org-file-apps)
(add-to-list 'org-file-apps '("\\.pdf\\'" . org-pdfview-open))
(add-to-list 'org-file-apps '("\\.pdf::\\([[:digit:]]+\\)\\'" . org-pdfview-open))
```

If org-pdfview should open PDF on the given page, I'll search in my installation for the error.

**Comment by markus1189** [comment]
At least for me it worked.  As said above I can't test it currently so I can come back to you on the weekend unless you find an error in your installation.

**Comment by Keks-Dose** [comment]
Did it work for you with current orgmode installation?

**Comment by markus1189** [comment]
Well... I have to admit that I totally forgot about that during the weekend, sorry!  I will make sure to test this on Thursday.

**Comment by markus1189** [comment]
Just tested it and it works here.  Not sure why it does not work for you, but you might want to jump to `org-pdfview.el` and call `eval-defun` with a prefix argument (`C-u C-M-X` for me) to instrument it for debugging.  Then you should be able to see what the `page` variable is by trying to open the link and stepping through the code.

**Comment by Keks-Dose** [comment]
OK, I get a message:
`Making pre-command-hook local to XY.pdf while let-bound!`
?

**Comment by markus1189** [comment]
Now idea where that comes from.  Do you see that while debugging or while opening a link?

**Comment by Keks-Dose** [comment]
I open org-pdfview.el and type `C-u C-M-X`. Then I open the org-file with the link and try to open the link using C-c C-o. Then the message appears.

**Comment by markus1189** [comment]
And if you then step through the code and inspect what the bound value of
`page` is? Org link for edebug in case you don't know it:
[[info:elisp#Edebug][info:elisp#Edebug]]

**Comment by Keks-Dose** [comment]
Took some minutes. Point inside org-pdfview.el to `(defun org-pdfview-open...`, C-u C-M-X, open the *.org-file, C-c C-o on the link and get the message: `pdf-view-goto-page: No such page: 0` So somehow the page of the link is wrong.

**Comment by markus1189** [comment]
Hard to say what is the issue here.  You could try to start emacs as `emacs -Q`, eval the required definitions and see if you can reproduce it there, if it is the case you can send me a step-by-step list so I can try to reproduce the error.

**Comment by Keks-Dose** [comment]
OK, I'll restart with a clean .emacs and see. Thank you for your help!

**Comment by Keks-Dose** [comment]
Pablo S. Casas published a solution on the emacs-orgmode mailinglist on [July, 24](http://lists.gnu.org/archive/html/emacs-orgmode/2016-07/msg00409.html). My initial setup, which did not work with Emacs 24.5 and orgmode 8.2 / 8.3:

```
(eval-after-load 'org '(require 'org-pdfview))
(delete '("\\.pdf\\'" . default) org-file-apps)
(add-to-list 'org-file-apps '("\\.pdf\\'" . org-pdfview-open))
(add-to-list 'org-file-apps '("\\.pdf::\\([[:digit:]]+\\)\\'" . org-pdfview-
open))
```

Setup now and working (PDF opened on a given page):

```
 (eval-after-load 'org '(require 'org-pdfview))
 (delete '("\\.pdf\\'" . default) org-file-apps)

(add-to-list 'org-file-apps '("\\.pdf\\'" . (org-pdfview-open link)))
(add-to-list 'org-file-apps '("\\.pdf::\\(\\d+\\)\\'" . (org-pdfview-open 
link)))
```

Unfortunately there is no more "sexp" case in `org-file-apps' in development version, as the maintainer wrote in the next post. So the whole thing will be back on the agenda with the next major update of orgmode. But for the time being I close the question.

**Comment by miroba** [comment]
For anyone looking to get this working with orgmode version 9.0.

Use: 
`(add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))
(add-to-list 'org-file-apps '("\\.pdf::\\([[:digit:]]+\\)\\'" . (lambda (file link) (org-pdfview-open link))))`
