### ISSUE TITLE
org-pdfview code for .emacs doesn't work with new release of orgmode v. 9.0

### ISSUE THREAD

**Issue by Keks-Dose** [markus1189/org-pdfview#14]
See my description of the error here:

https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00169.html

In a nutshell:

org-file-apps no longer accepts S-expressions as commands.

**Comment by markus1189** [comment]
If I understand that, the solution is to simply put

```
(add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))
```

in there instead of the two lines that are currently proposed?

**Comment by Keks-Dose** [comment]
Yes! If not done yet, would you please change your documentation? Thank you!
