### ISSUE TITLE
Error initializing emacs

### ISSUE THREAD

**Issue by shersk2** [markus1189/org-pdfview#15]
Warning (initialization): An error occurred while loading `/home/$$$$$/.emacs':

Symbol's value as variable is void: <!DOCTYPE

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

----------------------------------------------------------DEBUGGING OUTPUT BELOW-------------------------------------

Debugger entered--Lisp error: (void-variable <!DOCTYPE)
  eval-buffer(#<buffer  *load*-189005> nil "/home/$$$$$/.emacs.d/lisp/org-pdfview.el" nil t)  ; Reading at buffer position 14
  load-with-code-conversion("/home/$$$$$/.emacs.d/lisp/org-pdfview.el" "/home/shersk2/.emacs.d/lisp/org-pdfview.el" nil t)
  require(org-pdfview)
  eval-buffer(#<buffer  *load*> nil "/home/$$$$$/.emacs" nil t)  ; Reading at buffer position 2054
  load-with-code-conversion("/home/$$$$$/.emacs" "/home/$$$$$/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by alezost** [comment]
I doubt this is a problem of `org-pdfview`.  Check your `/home/shersk2/.emacs.d/lisp/org-pdfview.el`, it looks like it contains "<!DOCTYPE" (it shouldn't!)

**Comment by markus1189** [comment]
Thanks @alezost for stepping in.  @shersk2 I think alezost is right, look into your `org-pdfview.el`, I assume that you downloaded the wrong file. 

You should install it from elpa, otherwise my guess is you downloaded from GitHub, but instead of using the `raw` version you downloaded the html page showing the code by accident ;)

**Comment by shersk2** [comment]
You are right! Thanks. 

I see that org-pdfview is part of melpa, so then I am better off installing it from there?

**Comment by markus1189** [comment]
Yes ;) I am closing this then, good that you found the error.
