### ISSUE TITLE
Requires fixed obsolete version of pdf-tools

### ISSUE THREAD

**Issue by olberger** [markus1189/org-pdfview#16]
Hi.

I seem to have the following error poping up when trying to debug other matters (emacs -Q --batch --eval "(progn (package-initialize) (require 'notmuch) (message epg-gpg-program))"):

Unable to activate package ‘org-pdfview’.
Required package ‘pdf-tools-0.40’ is unavailable

AFAIU, this means that pdf-tools-0.40 is too old: v. 0.80 is currently installed in my setup.

Any clues how to fix this ?

**Comment by markus1189** [comment]
Can you try what happens if you change this line https://github.com/markus1189/org-pdfview/blob/master/org-pdfview.el#L9

from

```
;; Package-Requires: ((org "6.01") (pdf-tools "0.40"))
```

to

```
;; Package-Requires: ((org "6.01") (pdf-tools "0.80"))
```

**Comment by olberger** [comment]
I had to change the version in org-pdfview-pkg.el in the elpa installation of the package too, to make it want the right version of pdf-tools.

Thanks.

Dunno if there are side effects, though.

**Comment by markus1189** [comment]
I can update the version in the elpa package and release it.  If you want to do a pull request for the change, that would be appreciated as well :)
