### ISSUE TITLE
jump to annotation?

### ISSUE THREAD

**Issue by titaniumbones** [markus1189/org-pdfview#5]
politza suggests in politza/pdf-tools#134 that it should be possible to link not only to a page but directly to the location of an annotation.  How would you suggest I go about adding support for this to the pdfview link syntax? If I can figure it out would you be amenable to such an addition?

Thanks!

**Comment by markus1189** [comment]
Sounds good to me ;)

I guess it would be best to add another link type as done for `pdfview` https://github.com/markus1189/org-pdfview/blob/master/org-pdfview.el#L39.

Then you can just define the two functions that open and export the links to the annotation.  Depending on the fact whether you can also store links to annotations, you also have to add it as shown in https://github.com/markus1189/org-pdfview/blob/master/org-pdfview.el#L40.

Let me know how it goes.

Best,
Markus

**Comment by titaniumbones** [comment]
> I guess it would be best to add another link type as done for pdfview https://github.com/markus1189/org-pdfview/blob/master/org-pdfview.el#L39.

could one instead add another delimiter after the page, to the pdfview type? pdfview:/path/to/pdf::page++co-ordinate?

**Comment by markus1189** [comment]
If that works without ambiguities it's fine for me, too.  Of course old links should still work so the default behavior when the coordinate is missing should work as previously.

**Comment by titaniumbones** [comment]
see pull request #7
