### ISSUE TITLE
add completion

### ISSUE THREAD

**Issue by titaniumbones** [markus1189/org-pdfview#6]
the pdfview link type doen't provide file name completion. Is this easy to add?

**Comment by markus1189** [comment]
To be honest, I always use the `store` feature of org mode to save links.  In what concrete case do you miss autocompletion that works with other org-mode links?

**Comment by titaniumbones** [comment]
trying to link to a file that is somewhere close to the current file,
e.g. ../Readings/some-file.pdf

**Comment by markus1189** [comment]
and this works with other org links?  I use `hippie-expand` which works for me as auto completion of files.

I have no clue what the necessary change looks like, if you want to add it, feel free to do so ;)

**Comment by titaniumbones** [comment]
I just added completion here:
https://github.com/titaniumbones/org-pdfview/commit/e1f70b20be0bf0ea8ccd552a6c63192a6ce47493

can't submit another pull request I guess, but it's a very simple patch if you want it.
